version: "3.9"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - firestore_emulator
    environment:
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - FIRESTORE_PORT=$FIRESTORE_PORT
      - FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST}
      - PORT=${PORT}
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - PORT=${FIRESTORE_PORT}
    ports:
      - "${FIRESTORE_PORT}:${FIRESTORE_PORT}"
