version: "3.9"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      firestore_emulator: 
        condition: 
          service_healthy
    environment:
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - FIRESTORE_PORT=$FIRESTORE_PORT
      - FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECONDS_TO_EXPIRE=${JWT_SECONDS_TO_EXPIRE}
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - PORT=${FIRESTORE_PORT}
    ports:
      - "${FIRESTORE_PORT}:${FIRESTORE_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
