name: 'Deploy to GCP - Dev'

on: 
  workflow_run:
    workflows: [Build and test]
    types: [completed]
    branches: [main, feature/deploy-to-gcp]

jobs:
  deploy-to-gcp:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: ${{ secrets.USERS_SERVICE_DEPLOYER_SA_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: hashicorp/setup-terraform@v2
      - name: Deploy
        run: terraform apply --auto-approve -replace=null_resource.build_and_push_container_image
        working-directory: ./deploy/gcp/environments/dev
